version: '3.9'

services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=proyecto
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: ./Frontend_mejorado
    container_name: vue_frontend
    volumes:
      - ./Frontend_mejorado:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
