# backend/Dockerfile

FROM python:3.12-slim

# Evita archivos .pyc y buffers en stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instala dependencias necesarias para compilar paquetes
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    musl-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Instala dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código del proyecto
COPY . .

# Inicia el servidor con Gunicorn
CMD ["gunicorn", "proyecto_django.wsgi:application", "--bind", "0.0.0.0:8000"]
